std_msgs/Header header
float32 interval_time
float32 process_time
float32 mergin
float32 mergin_estimated
float32 total_time
float32 preprocess_time
float32 icp_time
float32 incremental_time
float32 match_time
float32 delete_time
float32 solve_time

int32 scan_point_raw_size
int32 scan_point_size
int32 feats_from_map_num
int32 effect_feat_num
int32 tree_size_start
int32 tree_size_end
int32 delete_size
int32 added_point_size
float32 downsize_coef


float32 gyro_bias_x
float32 gyro_bias_y
float32 gyro_bias_z
float32 acc_bias_x
float32 acc_bias_y
float32 acc_bias_z

string status